vich_uploader:
    db_driver: orm

    mappings:
        demande_files:
            uri_prefix: /uploads/demandes
            upload_destination: '%kernel.project_dir%/public/uploads/demandes'
            namer: vich_uploader.namer_uniqid