
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_home
        permanent: true

app_home:
    path: /home
    controller: App\Controller\HomeController::index

app_demande_conge:
    path: /demande-conge
    controller: App\Controller\DemandeCongeController::index

app_demande_conge_new:
    path: /demande-conge/new
    controller: App\Controller\DemandeCongeController::new

# Bulletin de paie (Payroll Slip) Routes
app_bulletinpaie_index:
    path: /bulletinpaie
    controller: App\Controller\BulletinpaieController::index

app_bulletinpaie_new:
    path: /bulletinpaie/new
    controller: App\Controller\BulletinpaieController::new

app_bulletinpaie_show:
    path: /bulletinpaie/{id}
    controller: App\Controller\BulletinpaieController::show

app_bulletinpaie_edit:
    path: /bulletinpaie/{id}/edit
    controller: App\Controller\BulletinpaieController::edit


app_bulletinpaie_delete:
    path: /bulletinpaie/{id}
    controller: App\Controller\BulletinpaieController::delete
    methods: [DELETE, POST]
    